esphome:
  name: apflashtest

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Pft4Jz0MmsvcJRg4TWfrbKvVEfwQO0EdUiB5GiRvDSQ="

ota:
  password: "bcfd4cba73672673e9db60b26046ed7f"

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apflashtest Fallback Hotspot"
    password: "uzJidUwi20wE"

web_server:
  local: true