esphome:
  name: testboi

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "499a8216c6cdd696cd451b0fd6f3338a"

wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
  ssid: "wuhotspot"
  password: "hotspotwu"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ddt-Distance-Clicker"
    password: "HUfrWyO4jABC"

captive_portal:


switch:
  - platform: gpio
    name: "Relay"
    id: relay1
    pin: GPIO23
    
binary_sensor:
  - platform: gpio
    name: "mod1"
    id: 'mod1'
    pin: 
      number: GPIO34
    on_press:
      then:
        - switch.turn_on: relay1
    on_release:
      then:
        - switch.turn_off: relay1
